apiVersion: v1
name: seq
version: 2022.1.7647
appVersion: 2022.1.7647
description: Seq is the easiest way for development teams to capture, search and visualize structured log events! This page will walk you through the very quick setup process.
keywords:
- seq
- structured
- logging
home: https://datalust.co/seq
icon: https://avatars1.githubusercontent.com/u/5898109?s=200&v=4
sources:
- https://github.com/datalust/helm.datalust.co
maintainers:
- name: nblumhardt
  email: nblumhardt@datalust.co
- name: KodrAus
  email: amannix@datalust.co
